name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKER_IMAGE_TAG }} --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Tailscale
       uses: tailscale/github-action@v2
       with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:runner

     - name: Deploy to Raspberry Pi
       run: |
         ssh -o "StrictHostKeyChecking no" keshav@raspi "
         docker pull ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKER_IMAGE_TAG }}
         docker stop ${{ secrets.CONTAINER_NAME }} > /dev/null 2>&1 || true
         docker rm ${{ secrets.CONTAINER_NAME }} > /dev/null 2>&1 || true
         docker run -d --name ${{ secrets.CONTAINER_NAME }} -p ${{ env.EXPOSED_PORT }}:80 ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKER_IMAGE_TAG }}
         "
