name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t abhishekram404/dnd-spellbook:latest --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Tailscale
       uses: tailscale/github-action@v2
       with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          
     - name: Deploy to Raspberry Pi
       run: |
         docker pull abhishekram404/dnd-spellbook:latest
         docker stop dnd-spellbook > /dev/null 2>&1 || true
         docker rm dnd-spellbook > /dev/null 2>&1 || true
         docker run -d --name dnd-spellbook -p 4840:80 abhishekram404/dnd-spellbook:latest
