name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t abhishekram404/dnd-spellbook:latest .
        docker push abhishekram404/dnd-spellbook:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH to Raspberry Pi and Deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        port: ${{ secrets.PI_PORT }}
        script: |
          docker pull abhishekram404/dnd-spellbook:latest
          docker stop dnd-spellbook || true
          docker rm dnd-spellbook || true
          docker run -d --name dnd-spellbook -p 4840:80 abhishekram404/dnd-spellbook:latest
